USE [master]
GO

/****** Object:  Database [ActionGames]    Script Date: 5/9/2024 14:06:27 ******/
CREATE DATABASE [ActionGames]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ActionGames', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ActionGames.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ActionGames_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ActionGames_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ActionGames].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ActionGames] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ActionGames] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ActionGames] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ActionGames] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ActionGames] SET ARITHABORT OFF 
GO

ALTER DATABASE [ActionGames] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ActionGames] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ActionGames] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ActionGames] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ActionGames] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ActionGames] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ActionGames] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ActionGames] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ActionGames] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ActionGames] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ActionGames] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ActionGames] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ActionGames] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ActionGames] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ActionGames] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ActionGames] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ActionGames] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ActionGames] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ActionGames] SET  MULTI_USER 
GO

ALTER DATABASE [ActionGames] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ActionGames] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ActionGames] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ActionGames] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ActionGames] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ActionGames] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ActionGames] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ActionGames] SET  READ_WRITE 
GO

