# Generated by Django 5.1 on 2024-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='foto',
            field=models.ImageField(default='imagen', upload_to='imagenes'),
        ),
    ]
