# Generated by Django 5.1 on 2024-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_juego_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='nombre_compania',
            field=models.TextField(max_length=255),
        ),
    ]
